name: flutter_printer_register_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-265.0.dev

dependencies:
  flutter:
    sdk: flutter
  thermal_printer: ^1.0.5        # TCP/BLE/BT/USB Connector
  esc_pos_utils_plus: ^2.0.3      # ESC/POS Ticket-Generator
  intl: ^0.19.0                   # Datumsformatierung
  permission_handler: ^11.3.1     # Runtime-Permissions (Android 12+)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
